[package]
name = "avant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
from-pest = "0.3.2"
pest = "2.7.4"
pest_derive = "2.7.4"
